security:
  jwt:
    # 32位密钥
    secret-key: LZVtT5pB1PFfu2A2CsUpI7oIYcj7zfLl
    # 15分钟
    expire-access: 900000
    # 7天
    expire-refresh: 604800000
# 验证码参数
captcha:
  classify: arithmetic
  len: 2

# minio存储服务
minio:
  access-key: minio
  secret-key: 123456
  endpoint: http://127.0.0.1:9000
  bucket:  test
